services:
  db:
    image: postgres:16.8
    container_name: desafio-inscritos
    environment:
      POSTGRES_USER: developerDB
      POSTGRES_PASSWORD: developerDB
      POSTGRES_DB: developerDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: